version: 0.1

phases:
  install:
    commands:
      - /usr/local/bin/config
  pre_build:
    commands:
      - echo "==> pre-build"
  build:
    commands:
      - make
  post_build:
    commands:
      - /usr/local/bin/ci-cd -p

